//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseRegiman
    {
        public int ExerciseRegimenID { get; set; }
        public int ExerciseID { get; set; }
        public int RegimenID { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual Regiman Regimen { get; set; }
    }
}
