//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.ExerciseRegimen = new HashSet<ExerciseRegimen>();
            this.ExerciseSequences = new HashSet<ExerciseSequence>();
        }
    
        public int ExerciseID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ExerciseRegimen> ExerciseRegimen { get; set; }
        public virtual ICollection<ExerciseSequence> ExerciseSequences { get; set; }
    }
}
