//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseStep
    {
        public ExerciseStep()
        {
            this.Joints = new HashSet<Joint>();
        }
    
        public int ExerciseStepID { get; set; }
        public int DelayTime { get; set; }
        public string Instructions { get; set; }
        public int ExerciseSequenceID { get; set; }
    
        public virtual ExerciseSequence ExerciseSequence { get; set; }
        public virtual ICollection<Joint> Joints { get; set; }
    }
}
