//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joint
    {
        public int JointID { get; set; }
        public int Angle { get; set; }
        public int JointNumber { get; set; }
        public int Tolerance { get; set; }
        public int ExerciseStepID { get; set; }
    
        public virtual ExerciseStep ExerciseStep { get; set; }
    }
}
