//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.PatientRegimen = new HashSet<PatientRegimen>();
        }
    
        public int PatientID { get; set; }
        public int TherapistID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedDate { get; set; }
        public string Calibration { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<PatientRegimen> PatientRegimen { get; set; }
    }
}
