//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitrunetics
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegimen
    {
        public int PatientRegimenID { get; set; }
        public int PatientID { get; set; }
        public int RegimenID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Regiman Regimen { get; set; }
    }
}
